name: Lint
on:
  push:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install
        run: |
          set -eux
          go install golang.org/x/lint/golint@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
      - name: golint
        run: golint -set_exit_status=1 ./...
      - name: gosec
        run: gosec -quiet -stdout -fmt golint ./...
      - name: golangci-lint
        run: golangci-lint run

